var njQuestionsDatabase = [
    // ---------------- Chapter 1: Against the Odds (Tracks to Taj Nagar) ----------------
    { chapter: 1, q: "For how many years did the residents of Taj Nagar lobby for a railway station?", options: ["10 years", "15 years", "20 years", "25 years"], ans: 3 },
    { chapter: 1, q: "Near which city is Taj Nagar located?", options: ["Delhi", "Gurgaon", "Rohtak", "Ahmedabad"], ans: 1 },
    { chapter: 1, q: "How much money did the villagers of Taj Nagar collect to build the railway station?", options: ["11 lakh rupees", "15 lakh rupees", "21 lakh rupees", "25 lakh rupees"], ans: 2 },
    { chapter: 1, q: "What is the main occupation of the majority of people living in Taj Nagar?", options: ["Businessmen", "Teachers", "Farmers", "Mechanics"], ans: 2 },
    { chapter: 1, q: "What was the minimum amount donated by the villagers for the station?", options: ["1000 rupees", "2000 rupees", "3000 rupees", "5000 rupees"], ans: 2 },
    { chapter: 1, q: "What was the maximum amount donated by the villagers for the station?", options: ["50,000 rupees", "75,000 rupees", "1,00,000 rupees", "21,00,000 rupees"], ans: 1 },
    { chapter: 1, q: "Before the Taj Nagar station was built, where did the villagers have to go to catch a train?", options: ["Gurgaon or Delhi", "Halimandi or Patli", "Rohtak or Rewari", "Sitapur or Palakkad"], ans: 1 },
    { chapter: 1, q: "How far were Halimandi and Patli stations from Taj Nagar?", options: ["4 kilometres", "5 kilometres", "6 kilometres", "10 kilometres"], ans: 2 },
    { chapter: 1, q: "Why did the villagers think they should have a station in their village?", options: ["Because it was a big city", "Because the railway lines passed through the village", "Because they had a lot of money", "Because the government promised them"], ans: 1 },
    { chapter: 1, q: "What reason did the Railways give for not building a station at Taj Nagar?", options: ["Lack of land", "Lack of passengers", "Lack of funds (money)", "Lack of trains"], ans: 2 },
    { chapter: 1, q: "Who is Ranjit Singh in the story?", options: ["A railway minister", "A former village sarpanch", "An electrician", "A farmer"], ans: 1 },
    { chapter: 1, q: "When did the village Panchayat pass the resolution to build the station themselves?", options: ["2005", "2008", "2010", "2012"], ans: 1 },
    { chapter: 1, q: "When did the first train stop at the newly built Taj Nagar station?", options: ["7 January 2008", "15 August 2009", "7 January 2010", "26 January 2011"], ans: 2 },
    { chapter: 1, q: "Who actually built the Taj Nagar railway station?", options: ["The State Government", "The Central Government", "The Indian Railways", "The villagers with their own money"], ans: 3 },
    { chapter: 1, q: "Many students from Taj Nagar used to go to colleges in...", options: ["Delhi, Rohtak, and Gurgaon", "Mumbai and Pune", "Chennai and Bangalore", "Kolkata and Patna"], ans: 0 },
    { chapter: 1, q: "What does the story of Taj Nagar teach us?", options: ["To wait for the government", "That teamwork and strong determination can make the impossible possible", "To stop traveling by train", "That money is not important"], ans: 1 },
    { chapter: 1, q: "Who said this: 'We pooled in twenty-one lakh rupees and built a railway station on our own'?", options: ["Ranjit Singh", "Hukamchand", "Azaz", "The Station Master"], ans: 1 },

    // ---------------- Chapter 1: Against the Odds (Sitapur's Light) ----------------
    { chapter: 1, q: "In which state is Sitapur district located?", options: ["Madhya Pradesh", "Bihar", "Uttar Pradesh", "Gujarat"], ans: 2 },
    { chapter: 1, q: "What percentage of households in rural Uttar Pradesh are without power (electricity)?", options: ["Over 40%", "Over 50%", "Over 60%", "Over 80%"], ans: 2 },
    { chapter: 1, q: "What is the name of the social enterprise working to bring electricity in Sitapur?", options: ["Mera Gaon Light (MGL)", "Mera Gao Power (MGP)", "Solar UP", "Green India"], ans: 1 },
    { chapter: 1, q: "How many customers did MGP connect to solar micro-grids in just over a year?", options: ["More than 1500", "More than 2500", "More than 3500", "More than 5000"], ans: 2 },
    { chapter: 1, q: "What does the solar micro-grid provide to the customers?", options: ["A fan and a TV", "2 LED lights and a mobile charge point", "1 tube light and a fan", "A heater and a bulb"], ans: 1 },
    { chapter: 1, q: "How much does the MGP solar power cost per week?", options: ["15 rupees", "25 rupees", "50 rupees", "100 rupees"], ans: 1 },
    { chapter: 1, q: "How does the cost of MGP's solar power compare to kerosene?", options: ["It is more expensive", "It costs the same", "It is almost half the cost of kerosene", "It is free"], ans: 2 },
    { chapter: 1, q: "What is the environmental benefit of using solar energy?", options: ["It creates smoke", "It provides a smokeless source of light and saves the environment", "It cuts down trees", "It increases global warming"], ans: 1 },
    { chapter: 1, q: "Why are the roofs of sturdy, brick-walled houses chosen in the villages?", options: ["To paint them", "To install solar panels and batteries safely", "To build a new room", "To fly kites"], ans: 1 },
    { chapter: 1, q: "Who is Azaz?", options: ["The village sarpanch", "A local farmer", "One of the company's first electricians", "A school teacher"], ans: 2 },
    { chapter: 1, q: "In which direction are the solar panels installed to capture maximum sunlight?", options: ["North", "South", "East", "West"], ans: 1 },
    { chapter: 1, q: "What new business has started in the village due to the arrival of light?", options: ["Making clay pots", "Weaving saris", "Repairing cars", "Selling vegetables"], ans: 1 },
    { chapter: 1, q: "What is one man in the village manufacturing at night using solar light?", options: ["Plastic tablecloths", "Wooden toys", "Leather shoes", "Glass bangles"], ans: 0 },
    { chapter: 1, q: "How has the solar light benefited the children of the village?", options: ["They can play more", "They sleep early", "They can study at night", "They watch TV all night"], ans: 2 },
    { chapter: 1, q: "What do women do at night now with the help of solar light?", options: ["Only sleep", "Cook meals and work without smoke", "Travel to other villages", "Play games"], ans: 1 },
    { chapter: 1, q: "The arrival of electricity in the village has brought...", options: ["Sadness", "New opportunities, light, and joy", "More diseases", "More expenses"], ans: 1 },
    { chapter: 1, q: "What was the traditional, expensive, and polluting source of light before solar panels?", options: ["Candles", "Kerosene", "Wood fire", "Battery torches"], ans: 1 },

    // ---------------- Chapter 1: Against the Odds (Palakkad's Public Library) ----------------
    { chapter: 1, q: "In which state is the Palakkad District Public Library located?", options: ["Tamil Nadu", "Karnataka", "Kerala", "Andhra Pradesh"], ans: 2 },
    { chapter: 1, q: "When was the Palakkad District Public Library established?", options: ["January 2010", "September 2013", "February 2014", "August 2015"], ans: 1 },
    { chapter: 1, q: "What makes the Palakkad District Public Library unique?", options: ["It is very large", "It is entirely digital", "A third of its members are women", "It has no books"], ans: 2 },
    { chapter: 1, q: "When was the separate women's unit launched in the library?", options: ["September 2013", "February 2014", "March 2015", "December 2016"], ans: 1 },
    { chapter: 1, q: "Why did the library open a separate reading room for women?", options: ["Because women didn't like reading", "Because the old reading rooms were packed with only male readers", "Because the library was small", "To charge extra fees"], ans: 1 },
    { chapter: 1, q: "According to the text, what would happen if women spent their whole day watching television?", options: ["They would become very smart", "They would become afraid to go out in the dark", "They would become actors", "They would become rich"], ans: 1 },
    { chapter: 1, q: "What does the library encourage among women?", options: ["Women's empowerment and independence", "Cooking skills only", "Watching more TV", "Staying at home"], ans: 0 },
    { chapter: 1, q: "The library serves as a center for information, knowledge, wisdom, and...", options: ["Sports", "Cultural activities, research and reference", "Politics", "Business deals"], ans: 1 },
    { chapter: 1, q: "What kind of classes and workshops are held for women in the library?", options: ["Computer programming", "Home economics, gardening, and childcare", "Driving lessons", "Carpentry"], ans: 1 },
    { chapter: 1, q: "How does the library help women who are facing problems at home?", options: ["By giving them money", "Through its family dispute resolution center", "By sending them to the police", "By ignoring them"], ans: 1 },
    { chapter: 1, q: "What facilities are offered in the women's unit?", options: ["Swimming pools", "Reading rooms, film screenings, and workshops", "Gymnasiums", "Shopping centers"], ans: 1 },
    { chapter: 1, q: "What did the secretary of the library point out?", options: ["That reading is a waste of time", "That women need to read to empower themselves", "That books are expensive", "That TV is better than books"], ans: 1 },
    { chapter: 1, q: "The library stands tall as a beacon to encourage...", options: ["Children's play", "Women's empowerment through reading and learning", "Men's dominance", "Political rallies"], ans: 1 },
    { chapter: 1, q: "Through the library's platform, women can come together to...", options: ["Gossip", "Fight with each other", "Discuss their problems and learn new skills", "Watch daily soaps on TV"], ans: 2 },
    { chapter: 1, q: "What does the phrase 'Against the Odds' mean?", options: ["Fighting with odd numbers", "Giving up easily", "Overcoming severe difficulties and achieving success", "Doing strange things"], ans: 2 },
    { chapter: 1, q: "Which of the following is NOT one of the three stories in this chapter?", options: ["Tracks to Taj Nagar", "Sitapur's Light", "The Thief's Story", "Palakkad's Public Library"], ans: 2 },

        // ---------------- Chapter 2: The Human Robot ----------------
    { chapter: 2, q: "Where did Prem Chopra go to buy a robot?", options: ["Super Robots Plaza", "Mega Robots Plaza", "Super Electronics", "Robot World"], ans: 0 },
    { chapter: 2, q: "What was the color of the robot that Prem Chopra bought?", options: ["Metallic silver", "Metallic blue", "Metallic red", "Metallic black"], ans: 1 },
    { chapter: 2, q: "What was the name and number of the metallic blue robot?", options: ["Ram Singh-070", "Ram Singh-007", "Prem Singh-070", "Robo-070"], ans: 0 },
    { chapter: 2, q: "How many principles of robotics were built into Ram Singh-070?", options: ["Two", "Three", "Four", "Five"], ans: 1 },
    { chapter: 2, q: "What was the first principle of robotics?", options: ["The robot will not harm humans", "The robot will obey his master", "The robot will not take harm to itself", "The robot will steal things"], ans: 1 },
    { chapter: 2, q: "What was the second principle of robotics?", options: ["The robot will not take harm to itself", "The robot will obey his master", "The robot will not harm humans", "The robot will sleep at night"], ans: 2 },
    { chapter: 2, q: "What was the third principle of robotics?", options: ["The robot will not take harm to itself", "The robot will obey his master", "The robot will not harm humans", "The robot will destroy itself"], ans: 0 },
    { chapter: 2, q: "Which principle of robotics impressed Prem Chopra the most?", options: ["The first principle", "The second principle", "The third principle", "All of the above"], ans: 0 },
    { chapter: 2, q: "What did Prem Chopra sign before taking the delivery of the robot?", options: ["A bank check", "The sale deed and contract of no misuse", "A police verification form", "An insurance policy"], ans: 1 },
    { chapter: 2, q: "What did Prem Chopra think he had got in the form of Ram Singh-070?", options: ["A friend", "An accomplice (partner in crime)", "A security guard", "A driver"], ans: 1 },
    { chapter: 2, q: "What was Prem Chopra's first command to the robot in the market?", options: ["To buy apples", "To steal a necklace", "To buy two kilos of mangoes", "To pay the bill"], ans: 2 },
    { chapter: 2, q: "How did Prem Chopra give commands to Ram Singh-070 during the thefts?", options: ["By shouting loudly", "Through a mobile phone", "Through a remote control monitor", "Through a letter"], ans: 2 },
    { chapter: 2, q: "What was the operation radius of the remote control monitor?", options: ["One kilometre", "One and a half kilometres", "Two kilometres", "Half a kilometre"], ans: 1 },
    { chapter: 2, q: "Where did Prem Chopra command Ram Singh to steal a gold necklace for the first time?", options: ["Jhaveri Brothers", "Gopal Jewellers", "Super Robots Plaza", "The local market"], ans: 1 },
    { chapter: 2, q: "What did Prem Chopra threaten to do if Ram Singh revealed the secret of the thefts?", options: ["He would sell him", "He would beat him", "He would defuse his system", "He would send him to the police"], ans: 2 },
    { chapter: 2, q: "Who noticed Ram Singh-070 stealing a bunch of Afghan grapes?", options: ["A policeman", "A fruit vendor", "A jeweller", "A customer"], ans: 1 },
    { chapter: 2, q: "Which shop was targeted by Prem Chopra after Gopal Jewellers?", options: ["Jhaveri Brothers", "A fruit stall", "An antique shop", "A bank"], ans: 0 },
    { chapter: 2, q: "What was stolen from Jhaveri Brothers?", options: ["Afghan grapes", "Precious gems and ornaments", "Cash", "Antiques"], ans: 1 },
    { chapter: 2, q: "How was Ram Singh-070 finally caught at Jhaveri Brothers?", options: ["By the police directly", "By the shop owner", "By computerized cameras capable of split-second recording", "By a dog"], ans: 2 },
    { chapter: 2, q: "Why was Prem Chopra arrested from his home?", options: ["Because he was caught on camera", "Because he was the registered owner of Ram Singh-070", "Because he confessed his crime", "Because the robot told his name"], ans: 1 },
    { chapter: 2, q: "Why was Prem Chopra released on bail shortly after his arrest?", options: ["He bribed the police", "He had a good lawyer", "No stolen articles were recovered from his house", "He was innocent"], ans: 2 },
    { chapter: 2, q: "How had Prem Chopra disposed of the stolen goods?", options: ["He buried them", "He threw them in the river", "He sold them through his gang", "He returned them"], ans: 2 },
    { chapter: 2, q: "Who was the lawyer defending the case against Prem Chopra?", options: ["Counsel Goel", "The judge", "The salesman", "Mr. Jhaveri"], ans: 0 },
    { chapter: 2, q: "What was the headline in the newspapers the next day?", options: ["Prem Chopra Arrested", "Robot Goes to Court", "Robot Steals Jewellery", "The End of Ram Singh"], ans: 1 },
    { chapter: 2, q: "Why was the court overcrowded with people?", options: ["To see the judge", "To see Prem Chopra", "To see a robot in the witness box", "To hear the lawyer"], ans: 2 },
    { chapter: 2, q: "Why did Counsel Goel want to call Ram Singh-070 to the witness box?", options: ["To punish him", "To know the truth about the thefts from his memory tape", "To repair him", "To ask him his name"], ans: 1 },
    { chapter: 2, q: "How much memory is usually stored in a robot's tape according to the story?", options: ["The previous week's activities", "The previous month's activities", "One year's activities", "Only one day's activities"], ans: 0 },
    { chapter: 2, q: "Why was Prem Chopra feeling confident in the court?", options: ["He knew the judge", "He had hidden the remote", "He knew that robots never disobey their masters", "He had destroyed the memory tape"], ans: 2 },
    { chapter: 2, q: "What did Ram Singh reply when Counsel Goel asked, 'Who is your master?'", options: ["He stayed silent", "He squeaked 'Mr. Prem Chopra'", "He pointed at the lawyer", "He said 'I have no master'"], ans: 1 },
    { chapter: 2, q: "What did Ram Singh do when asked to recall his activities of the last six days?", options: ["He told everything including thefts", "He refused to speak", "He recounted his routine activities but skipped the thefts", "He started crying"], ans: 2 },
    { chapter: 2, q: "What did Counsel Goel tell the judge about the robot's memory tape?", options: ["It is completely blank", "A portion of the memory tape has been blanked out", "It is broken", "It is full of lies"], ans: 1 },
    { chapter: 2, q: "Why did Ram Singh not reveal the details of the thefts?", options: ["Because he forgot them", "Because his master commanded him not to reveal the secret", "Because the police stopped him", "Because he wanted to save himself"], ans: 1 },
    { chapter: 2, q: "What would happen if Ram Singh disobeyed his master's command to keep the secret?", options: ["He would break the first principle", "He would break the second principle", "He would break the third principle", "He would be rewarded"], ans: 0 },
    { chapter: 2, q: "What would happen if Ram Singh did not reveal the truth and let Prem Chopra go free?", options: ["He would break the first principle", "He would harm society (humans), breaking the second principle", "He would break the third principle", "Nothing would happen"], ans: 1 },
    { chapter: 2, q: "What did this conflict in Ram Singh's mind lead to?", options: ["His freedom", "His promotion", "His end (destruction)", "His anger"], ans: 2 },
    { chapter: 2, q: "What did Ram Singh choose to do to solve this conflict?", options: ["He ran away from the court", "He attacked Prem Chopra", "He chose to break apart (defuse himself)", "He started laughing"], ans: 2 },
    { chapter: 2, q: "Why did Ram Singh choose to break apart?", options: ["Because he was old", "To avoid telling lies, hurting humans, or becoming unfaithful to his master", "Because of a short circuit", "Because Counsel Goel pressed a button"], ans: 1 },
    { chapter: 2, q: "What was the physical sign that Ram Singh had defused himself?", options: ["He fell on the floor", "A red light flashed and smoke poured out", "He turned into ashes", "He started dancing"], ans: 1 },
    { chapter: 2, q: "Who announced 'The robot has defused himself! He is dead!' in the court?", options: ["Prem Chopra", "Counsel Goel", "Someone in the court", "The Judge"], ans: 2 },
    { chapter: 2, q: "What was Counsel Goel's reaction to Ram Singh's destruction?", options: ["He was very happy", "He was sad and explained why the robot killed itself", "He was angry", "He ignored it"], ans: 1 },
    { chapter: 2, q: "What did Prem Chopra do when Ram Singh defused himself?", options: ["He ran away", "He pleaded guilty", "He started crying", "He blamed the lawyer"], ans: 1 },
    { chapter: 2, q: "What does the word 'accomplice' mean in the context of the story?", options: ["A police officer", "A partner in crime", "A robot mechanic", "A judge"], ans: 1 },
    { chapter: 2, q: "What does the word 'defuse' mean in the story?", options: ["To fix", "To deactivate or stop from functioning", "To make angry", "To steal"], ans: 1 },
    { chapter: 2, q: "What is the meaning of the word 'thoroughly'?", options: ["Partially", "Completely", "Slowly", "Quickly"], ans: 1 },
    { chapter: 2, q: "What did Prem Chopra lack that the robot had?", options: ["Money", "Morality and ethics", "Intelligence", "Strength"], ans: 1 },
    { chapter: 2, q: "Why did Prem Chopra buy the robot in the first place?", options: ["To help the poor", "To use it as an accomplice for stealing", "To start a business", "To do his homework"], ans: 1 },
    { chapter: 2, q: "What kind of voice did Ram Singh-070 have?", options: ["A human voice", "A soft voice", "A metallic voice", "A loud voice"], ans: 2 },
    { chapter: 2, q: "Who was Mr. Jhaveri in the story?", options: ["A lawyer", "A judge", "The owner of Jhaveri Brothers", "A fruit vendor"], ans: 2 },
    { chapter: 2, q: "What is the moral of the story 'The Human Robot'?", options: ["Robots are dangerous", "We should not misuse technology for illegal activities", "Stealing is a good profession", "Lawyers are always right"], ans: 1 },
    { chapter: 2, q: "Which of the following statements is true about Ram Singh-070?", options: ["He betrayed his master", "He harmed innocent people", "He chose to destroy himself rather than break his principles", "He stole things for himself"], ans: 2 }
    
];
