var njQuestionsDatabase = [
    // ---------------- Chapter 1: Against the Odds (Tracks to Taj Nagar) ----------------
    { chapter: 1, q: "For how many years did the residents of Taj Nagar lobby for a railway station?", options: ["10 years", "15 years", "20 years", "25 years"], ans: 3 },
    { chapter: 1, q: "Near which city is Taj Nagar located?", options: ["Delhi", "Gurgaon", "Rohtak", "Ahmedabad"], ans: 1 },
    { chapter: 1, q: "How much money did the villagers of Taj Nagar collect to build the railway station?", options: ["11 lakh rupees", "15 lakh rupees", "21 lakh rupees", "25 lakh rupees"], ans: 2 },
    { chapter: 1, q: "What is the main occupation of the majority of people living in Taj Nagar?", options: ["Businessmen", "Teachers", "Farmers", "Mechanics"], ans: 2 },
    { chapter: 1, q: "What was the minimum amount donated by the villagers for the station?", options: ["1000 rupees", "2000 rupees", "3000 rupees", "5000 rupees"], ans: 2 },
    { chapter: 1, q: "What was the maximum amount donated by the villagers for the station?", options: ["50,000 rupees", "75,000 rupees", "1,00,000 rupees", "21,00,000 rupees"], ans: 1 },
    { chapter: 1, q: "Before the Taj Nagar station was built, where did the villagers have to go to catch a train?", options: ["Gurgaon or Delhi", "Halimandi or Patli", "Rohtak or Rewari", "Sitapur or Palakkad"], ans: 1 },
    { chapter: 1, q: "How far were Halimandi and Patli stations from Taj Nagar?", options: ["4 kilometres", "5 kilometres", "6 kilometres", "10 kilometres"], ans: 2 },
    { chapter: 1, q: "Why did the villagers think they should have a station in their village?", options: ["Because it was a big city", "Because the railway lines passed through the village", "Because they had a lot of money", "Because the government promised them"], ans: 1 },
    { chapter: 1, q: "What reason did the Railways give for not building a station at Taj Nagar?", options: ["Lack of land", "Lack of passengers", "Lack of funds (money)", "Lack of trains"], ans: 2 },
    { chapter: 1, q: "Who is Ranjit Singh in the story?", options: ["A railway minister", "A former village sarpanch", "An electrician", "A farmer"], ans: 1 },
    { chapter: 1, q: "When did the village Panchayat pass the resolution to build the station themselves?", options: ["2005", "2008", "2010", "2012"], ans: 1 },
    { chapter: 1, q: "When did the first train stop at the newly built Taj Nagar station?", options: ["7 January 2008", "15 August 2009", "7 January 2010", "26 January 2011"], ans: 2 },
    { chapter: 1, q: "Who actually built the Taj Nagar railway station?", options: ["The State Government", "The Central Government", "The Indian Railways", "The villagers with their own money"], ans: 3 },
    { chapter: 1, q: "Many students from Taj Nagar used to go to colleges in...", options: ["Delhi, Rohtak, and Gurgaon", "Mumbai and Pune", "Chennai and Bangalore", "Kolkata and Patna"], ans: 0 },
    { chapter: 1, q: "What does the story of Taj Nagar teach us?", options: ["To wait for the government", "That teamwork and strong determination can make the impossible possible", "To stop traveling by train", "That money is not important"], ans: 1 },
    { chapter: 1, q: "Who said this: 'We pooled in twenty-one lakh rupees and built a railway station on our own'?", options: ["Ranjit Singh", "Hukamchand", "Azaz", "The Station Master"], ans: 1 },

    // ---------------- Chapter 1: Against the Odds (Sitapur's Light) ----------------
    { chapter: 1, q: "In which state is Sitapur district located?", options: ["Madhya Pradesh", "Bihar", "Uttar Pradesh", "Gujarat"], ans: 2 },
    { chapter: 1, q: "What percentage of households in rural Uttar Pradesh are without power (electricity)?", options: ["Over 40%", "Over 50%", "Over 60%", "Over 80%"], ans: 2 },
    { chapter: 1, q: "What is the name of the social enterprise working to bring electricity in Sitapur?", options: ["Mera Gaon Light (MGL)", "Mera Gao Power (MGP)", "Solar UP", "Green India"], ans: 1 },
    { chapter: 1, q: "How many customers did MGP connect to solar micro-grids in just over a year?", options: ["More than 1500", "More than 2500", "More than 3500", "More than 5000"], ans: 2 },
    { chapter: 1, q: "What does the solar micro-grid provide to the customers?", options: ["A fan and a TV", "2 LED lights and a mobile charge point", "1 tube light and a fan", "A heater and a bulb"], ans: 1 },
    { chapter: 1, q: "How much does the MGP solar power cost per week?", options: ["15 rupees", "25 rupees", "50 rupees", "100 rupees"], ans: 1 },
    { chapter: 1, q: "How does the cost of MGP's solar power compare to kerosene?", options: ["It is more expensive", "It costs the same", "It is almost half the cost of kerosene", "It is free"], ans: 2 },
    { chapter: 1, q: "What is the environmental benefit of using solar energy?", options: ["It creates smoke", "It provides a smokeless source of light and saves the environment", "It cuts down trees", "It increases global warming"], ans: 1 },
    { chapter: 1, q: "Why are the roofs of sturdy, brick-walled houses chosen in the villages?", options: ["To paint them", "To install solar panels and batteries safely", "To build a new room", "To fly kites"], ans: 1 },
    { chapter: 1, q: "Who is Azaz?", options: ["The village sarpanch", "A local farmer", "One of the company's first electricians", "A school teacher"], ans: 2 },
    { chapter: 1, q: "In which direction are the solar panels installed to capture maximum sunlight?", options: ["North", "South", "East", "West"], ans: 1 },
    { chapter: 1, q: "What new business has started in the village due to the arrival of light?", options: ["Making clay pots", "Weaving saris", "Repairing cars", "Selling vegetables"], ans: 1 },
    { chapter: 1, q: "What is one man in the village manufacturing at night using solar light?", options: ["Plastic tablecloths", "Wooden toys", "Leather shoes", "Glass bangles"], ans: 0 },
    { chapter: 1, q: "How has the solar light benefited the children of the village?", options: ["They can play more", "They sleep early", "They can study at night", "They watch TV all night"], ans: 2 },
    { chapter: 1, q: "What do women do at night now with the help of solar light?", options: ["Only sleep", "Cook meals and work without smoke", "Travel to other villages", "Play games"], ans: 1 },
    { chapter: 1, q: "The arrival of electricity in the village has brought...", options: ["Sadness", "New opportunities, light, and joy", "More diseases", "More expenses"], ans: 1 },
    { chapter: 1, q: "What was the traditional, expensive, and polluting source of light before solar panels?", options: ["Candles", "Kerosene", "Wood fire", "Battery torches"], ans: 1 },

    // ---------------- Chapter 1: Against the Odds (Palakkad's Public Library) ----------------
    { chapter: 1, q: "In which state is the Palakkad District Public Library located?", options: ["Tamil Nadu", "Karnataka", "Kerala", "Andhra Pradesh"], ans: 2 },
    { chapter: 1, q: "When was the Palakkad District Public Library established?", options: ["January 2010", "September 2013", "February 2014", "August 2015"], ans: 1 },
    { chapter: 1, q: "What makes the Palakkad District Public Library unique?", options: ["It is very large", "It is entirely digital", "A third of its members are women", "It has no books"], ans: 2 },
    { chapter: 1, q: "When was the separate women's unit launched in the library?", options: ["September 2013", "February 2014", "March 2015", "December 2016"], ans: 1 },
    { chapter: 1, q: "Why did the library open a separate reading room for women?", options: ["Because women didn't like reading", "Because the old reading rooms were packed with only male readers", "Because the library was small", "To charge extra fees"], ans: 1 },
    { chapter: 1, q: "According to the text, what would happen if women spent their whole day watching television?", options: ["They would become very smart", "They would become afraid to go out in the dark", "They would become actors", "They would become rich"], ans: 1 },
    { chapter: 1, q: "What does the library encourage among women?", options: ["Women's empowerment and independence", "Cooking skills only", "Watching more TV", "Staying at home"], ans: 0 },
    { chapter: 1, q: "The library serves as a center for information, knowledge, wisdom, and...", options: ["Sports", "Cultural activities, research and reference", "Politics", "Business deals"], ans: 1 },
    { chapter: 1, q: "What kind of classes and workshops are held for women in the library?", options: ["Computer programming", "Home economics, gardening, and childcare", "Driving lessons", "Carpentry"], ans: 1 },
    { chapter: 1, q: "How does the library help women who are facing problems at home?", options: ["By giving them money", "Through its family dispute resolution center", "By sending them to the police", "By ignoring them"], ans: 1 },
    { chapter: 1, q: "What facilities are offered in the women's unit?", options: ["Swimming pools", "Reading rooms, film screenings, and workshops", "Gymnasiums", "Shopping centers"], ans: 1 },
    { chapter: 1, q: "What did the secretary of the library point out?", options: ["That reading is a waste of time", "That women need to read to empower themselves", "That books are expensive", "That TV is better than books"], ans: 1 },
    { chapter: 1, q: "The library stands tall as a beacon to encourage...", options: ["Children's play", "Women's empowerment through reading and learning", "Men's dominance", "Political rallies"], ans: 1 },
    { chapter: 1, q: "Through the library's platform, women can come together to...", options: ["Gossip", "Fight with each other", "Discuss their problems and learn new skills", "Watch daily soaps on TV"], ans: 2 },
    { chapter: 1, q: "What does the phrase 'Against the Odds' mean?", options: ["Fighting with odd numbers", "Giving up easily", "Overcoming severe difficulties and achieving success", "Doing strange things"], ans: 2 },
    { chapter: 1, q: "Which of the following is NOT one of the three stories in this chapter?", options: ["Tracks to Taj Nagar", "Sitapur's Light", "The Thief's Story", "Palakkad's Public Library"], ans: 2 }
];
