Var sciExerciseDB_Std8_Ch1 = [
    {
        chapter: 1,
        questionNumber: 1,
        marks: 3,
        q: "યોગ્ય શબ્દ પસંદ કરી ખાલી જગ્યાની પૂર્તતા કરો : (તરવા, પાણી, પાક, પોષકદ્રવ્યો, તૈયાર)",
        ans: "(a) એક સ્થાન પર એક જ પ્રકારના મોટી માત્રામાં ઉછેરવામાં આવતા છોડને <span style='color:#c2185b; font-weight:bold;'>પાક</span> કહે છે.<br><br>(b) પાક ઉગાડતા (રોપતાં) પહેલાંનો પ્રથમ તબક્કો જમીનને <span style='color:#c2185b; font-weight:bold;'>તૈયાર</span> કરવાનો હોય છે.<br><br>(c) ક્ષતિગ્રસ્ત બીજ પાણીની સપાટી પર <span style='color:#c2185b; font-weight:bold;'>તરવા</span> લાગશે.<br><br>(d) પાક ઉગાડવા માટે પર્યાપ્ત સૂર્યનો પ્રકાશ તેમજ જમીનમાંથી <span style='color:#c2185b; font-weight:bold;'>પાણી</span> તથા <span style='color:#c2185b; font-weight:bold;'>પોષકદ્રવ્યો</span> આવશ્યક છે.<br><br><div style='background-color:#fff3cd; border-left:5px solid #ffc107; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#856404;'><b>નિતેશ સરની શોર્ટકટ ટ્રિક:</b><br>યાદ રાખો: ખરાબ બીજ અંદરથી પોલાં (ખાલી) હોય છે, એટલે વજનમાં હલકા થઈ જાય અને <b>'તરવા'</b> લાગે! અને છોડને મોટા થવા શું જોઈએ? આપણા જેવું જ... પીવા <b>'પાણી'</b> અને ખાવા <b>'પોષકદ્રવ્યો'</b>!</span></div>"
    },
    {
        chapter: 1,
        questionNumber: 2,
        marks: 4,
        q: "કૉલમ-A માં આપેલાં શબ્દોને કૉલમ-B માં આપેલાં શબ્દો સાથે જોડો :",
        ans: "નીચે સાચા જવાબોની જોડ આપેલી છે:<br><br><div style='overflow-x:auto; background-color:#fdfdfd; border:1px solid #dee2e6; border-radius:8px;'><table style='width:100%; border-collapse:collapse; text-align:left;'><tr style='background-color:#17a2b8; color:white;'><th style='padding:12px; border:1px solid #dee2e6;'>કૉલમ - A</th><th style='padding:12px; border:1px solid #dee2e6;'>સાચો જવાબ (કૉલમ - B)</th></tr><tr><td style='padding:10px; border:1px solid #dee2e6;'>(i) ખરીફ પાક</td><td style='padding:10px; border:1px solid #dee2e6;'><span style='color:#28a745; font-weight:bold;'>(e) ડાંગર અને મકાઈ</span></td></tr><tr style='background-color:#f2f2f2;'><td style='padding:10px; border:1px solid #dee2e6;'>(ii) રવીપાક</td><td style='padding:10px; border:1px solid #dee2e6;'><span style='color:#28a745; font-weight:bold;'>(d) ઘઉં, ચણા, વટાણા</span></td></tr><tr><td style='padding:10px; border:1px solid #dee2e6;'>(iii) રાસાયણિક ખાતર</td><td style='padding:10px; border:1px solid #dee2e6;'><span style='color:#28a745; font-weight:bold;'>(b) યુરિયા અને સુપરફૉસ્ફેટ</span></td></tr><tr style='background-color:#f2f2f2;'><td style='padding:10px; border:1px solid #dee2e6;'>(iv) છાણિયું ખાતર</td><td style='padding:10px; border:1px solid #dee2e6;'><span style='color:#28a745; font-weight:bold;'>(c) પ્રાણીમળ, ગાયનું છાણ, મૂત્ર અને વનસ્પતિનો નકામો કચરો</span></td></tr></table></div><br><div style='background-color:#e2e3e5; border-left:5px solid #6c757d; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#383d41;'><b>નિતેશ સરની ટિપ્સ:</b><br><b>ખરીફ</b> એટલે ચોમાસું (જેને વધુ પાણી જોઈએ = ડાંગર). <b>રવી</b> એટલે શિયાળો (જેને ઓછું પાણી અને ઠંડી જોઈએ = ઘઉં/ચણા). રાસાયણિક એટલે ફેક્ટરીનું નામ (યુરિયા), અને છાણિયું તો નામ પરથી જ ખબર પડી જાય!</span></div>"
    },
    {
        chapter: 1,
        questionNumber: 3,
        marks: 2,
        q: "નીચેનાં દરેકનાં બે-બે ઉદાહરણ આપો :<br>(a) ખરીફ પાક<br>(b) રવીપાક",
        ans: "<b>(a) ખરીફ પાક:</b> <span style='color:#0275d8; font-weight:bold;'>ડાંગર (ચોખા) અને મકાઈ</span> (આ ઉપરાંત સોયાબીન, મગફળી, કપાસ પણ લખી શકાય).<br><br><b>(b) રવીપાક:</b> <span style='color:#d9534f; font-weight:bold;'>ઘઉં અને ચણા</span> (આ ઉપરાંત વટાણા, રાઈ, અળસી પણ લખી શકાય).<br><br><div style='background-color:#d4edda; border-left:5px solid #28a745; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#155724;'><b>નિતેશ સરની શોર્ટકટ ટ્રિક:</b><br>શબ્દો પર ધ્યાન આપો! <b>રવી</b> એટલે સૂર્ય (શિયાળામાં તડકો ગમે ને!). શિયાળામાં આપણે ગરમ-ગરમ <b>ઘઉંની રોટલી અને ચણા</b> ખાઈએ! જ્યારે ચોમાસામાં ભજીયાં સાથે <b>મકાઈ</b> ડોડા ખાવાની મજા આવે (ખરીફ).</span></div>"
    },
    {
        chapter: 1,
        questionNumber: 4,
        marks: 4,
        q: "નીચેનાં દરેક પર તમારા શબ્દોમાં એક-એક ફકરો લખો :<br>(a) ભૂમિને તૈયાર કરવી<br>(b) રોપણી<br>(c) નીંદામણ<br>(d) થ્રેશિંગ",
        ans: "<b><span style='color:#d32f2f;'>(a) ભૂમિને તૈયાર કરવી:</span></b> પાક ઉગાડતા પહેલાંનો આ પ્રથમ તબક્કો છે. ખેતરને હળ કે કલ્ટિવેટર (દાંતી) વડે ખેડવામાં આવે છે. ખેડ કરવાથી માટી ઉપર-નીચે થાય છે અને પોચી બને છે. પોચી માટીમાં મૂળ ઊંડે સુધી જઈ શકે છે અને શ્વસન કરી શકે છે. તે અળસિયાં અને સૂક્ષ્મજીવોની વૃદ્ધિમાં પણ મદદ કરે છે.<br><br><b><span style='color:#1976d2;'>(b) રોપણી (વાવણી):</span></b> પાક ઉત્પાદનનો આ સૌથી મહત્વનો તબક્કો છે. વાવણી પહેલાં સારી ગુણવત્તાવાળા, સ્વચ્છ અને તંદુરસ્ત બીજ પસંદ કરવામાં આવે છે. બીજ વાવવા માટે પરંપરાગત ઓજાર (ગરણી જેવું) અથવા આધુનિક 'વાવણીયા' (Seed Drill) નો ઉપયોગ થાય છે, જેથી બીજ સમાન અંતરે અને યોગ્ય ઊંડાઈએ વવાય.<br><br><b><span style='color:#388e3c;'>(c) નીંદામણ:</span></b> ખેતરમાં મુખ્ય પાકની સાથે ઊગી નીકળતી બિનજરૂરી અને નકામી વનસ્પતિને 'નીંદણ' કહે છે. આ નીંદણને દૂર કરવાની પ્રક્રિયાને નીંદામણ કહેવાય છે. નીંદણ એ પાકના ભાગનું પાણી, પોષકતત્વો, જગ્યા અને પ્રકાશ છીનવી લે છે. તેને દૂર કરવા ખુરપીનો ઉપયોગ થાય છે અથવા 2,4-D જેવા નીંદણનાશક રસાયણો છાંટવામાં આવે છે.<br><br><b><span style='color:#f57c00;'>(d) થ્રેશિંગ (ગાહવું):</span></b> લણણી કરેલા (કાપેલા) પાકના ડૂંડામાંથી દાણાઓને છૂટા પાડવાની પ્રક્રિયાને થ્રેશિંગ કહે છે. આ માટે 'થ્રેશર' નામના મશીનનો ઉપયોગ કરવામાં આવે છે. આજકાલ કાપણી (Harvesting) અને થ્રેશિંગ બંને એકસાથે કરી શકે તેવા 'કમ્બાઈન' (Combine) મશીનનો ઉપયોગ થાય છે.<br><br><div style='background-color:#e1f5fe; border-left:5px solid #03a9f4; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#01579b;'><b>નિતેશ સરની ટિપ્સ:</b><br>ક્રમ યાદ રાખો: <b>ખેતર ખેડો ➜ બીજ વાવો ➜ કચરો કાઢો ➜ દાણા છૂટા પાડો.</b> બસ, આ જ પ્રોસેસ પરથી આખા ફકરા જાતે લખી શકાશે!</span></div>"
    },
    {
        chapter: 1,
        questionNumber: 5,
        marks: 3,
        q: "સમજાવો કે કૃત્રિમ ખાતર કઈ રીતે કુદરતી ખાતરથી અલગ છે.",
        ans: "કૃત્રિમ ખાતર અને કુદરતી ખાતર વચ્ચેનો મુખ્ય તફાવત નીચે મુજબ છે:<br><br><div style='overflow-x:auto; background-color:#fdfdfd; border:1px solid #dee2e6; border-radius:8px;'><table style='width:100%; border-collapse:collapse; text-align:left; min-width:500px;'><tr style='background-color:#673ab7; color:white;'><th style='padding:10px; border:1px solid #dee2e6;'>મુદ્દાઓ</th><th style='padding:10px; border:1px solid #dee2e6;'>કૃત્રિમ ખાતર (Fertilizer)</th><th style='padding:10px; border:1px solid #dee2e6;'>કુદરતી ખાતર (Manure)</th></tr><tr><td style='padding:8px; border:1px solid #dee2e6;'><b>બનાવટ</b></td><td style='padding:8px; border:1px solid #dee2e6;'>તે રાસાયણિક પદાર્થ છે, જે <b>કારખાનાઓમાં</b> બને છે.</td><td style='padding:8px; border:1px solid #dee2e6;'>તે પ્રાકૃતિક પદાર્થ છે (છાણ, મળ, કચરો), જે <b>ખેતરમાં</b> બનાવી શકાય છે.</td></tr><tr style='background-color:#f2f2f2;'><td style='padding:8px; border:1px solid #dee2e6;'><b>સેન્દ્રીય પદાર્થો</b></td><td style='padding:8px; border:1px solid #dee2e6;'>તેનાથી જમીનને સેન્દ્રીય પદાર્થો (Humus) <b>પ્રાપ્ત થતા નથી.</b></td><td style='padding:8px; border:1px solid #dee2e6;'>તેનાથી જમીનને <b>ભરપૂર માત્રામાં</b> સેન્દ્રીય પદાર્થો મળે છે.</td></tr><tr><td style='padding:8px; border:1px solid #dee2e6;'><b>પોષકતત્વો</b></td><td style='padding:8px; border:1px solid #dee2e6;'>તેમાં N, P, K (નાઇટ્રોજન, ફૉસ્ફરસ, પોટેશિયમ) <b>ભરપૂર</b> હોય છે.</td><td style='padding:8px; border:1px solid #dee2e6;'>તેમાં વનસ્પતિ માટેના પોષકતત્વોની માત્રા <b>ઓછી</b> હોય છે.</td></tr><tr style='background-color:#f2f2f2;'><td style='padding:8px; border:1px solid #dee2e6;'><b>જમીનને નુકસાન</b></td><td style='padding:8px; border:1px solid #dee2e6;'>લાંબા ગાળે જમીનનું બંધારણ <b>બગાડે છે</b> અને જળ-પ્રદૂષણ કરે છે.</td><td style='padding:8px; border:1px solid #dee2e6;'>જમીનનું બંધારણ અને ભેજ-સંગ્રહ શક્તિ <b>સુધારે છે</b>.</td></tr></table></div><br><div style='background-color:#fff3cd; border-left:5px solid #ff9800; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#e65100;'><b>નિતેશ સરની શોર્ટકટ ટ્રિક:</b><br>કૃત્રિમ ખાતર એટલે <b>'ફાસ્ટ ફૂડ'</b> (તરત એનર્જી આપે પણ રોજ ખાવ તો નુકસાન કરે). કુદરતી ખાતર એટલે <b>'ઘરનું દેશી જમવાનું'</b> (શરીર/જમીન માટે કાયમ બેસ્ટ!).</span></div>"
    },
    {
        chapter: 1,
        questionNumber: 6,
        marks: 4,
        q: "સિંચાઈ એટલે શું ? પાણી બચાવતી સિંચાઈની બે પદ્ધતિઓનું વર્ણન કરો.",
        ans: "<b>સિંચાઈની વ્યાખ્યા:</b> સમયાંતરે ખેતરમાં પાણી પૂરું પાડવાની પ્રક્રિયાને સિંચાઈ કહે છે.<br><br>પાણીનો બચાવ કરતી બે આધુનિક પદ્ધતિઓ નીચે મુજબ છે:<br><br><b><span style='color:#0056b3;'>૧. ફુવારા પદ્ધતિ (Sprinkler System):</span></b><br>આ પદ્ધતિનો ઉપયોગ અસમતલ (ઊંચી-નીચી) ભૂમિ માટે થાય છે. આમાં મુખ્ય પાઇપ સાથે કાટખૂણે ફરતી નોઝલવાળી નાની પાઇપો જોડેલી હોય છે. જ્યારે પંપ દ્વારા મુખ્ય પાઇપમાં દબાણપૂર્વક પાણી મોકલાય છે, ત્યારે તે ગોળ ફરતી નોઝલમાંથી બહાર આવે છે. તેનો છંટકાવ છોડ પર એવી રીતે થાય છે <b>જાણે વરસાદ પડતો હોય!</b> રેતાળ જમીન માટે આ પદ્ધતિ ખૂબ ઉપયોગી છે.<br><br><b><span style='color:#28a745;'>૨. ટપક પદ્ધતિ (Drip System):</span></b><br>આ પદ્ધતિમાં પાઇપની મદદથી <b>પાણી ટીપે-ટીપે સીધું છોડના મૂળમાં જ પડે છે.</b> આથી તેને ટપક પદ્ધતિ કહે છે. ફળ આપતી વનસ્પતિના બગીચા અને વૃક્ષોને પાણી આપવાની આ સર્વોત્તમ પદ્ધતિ છે. આ પદ્ધતિમાં પાણીનો જરાય વ્યય (બગાડ) થતો નથી. તેથી તે પાણીની અછતવાળા વિસ્તારો માટે વરદાન સમાન છે.<br><br><div style='background-color:#f3e5f5; border-left:5px solid #9c27b0; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#4a148c;'><b>નિતેશ સરની ટિપ્સ:</b><br>જો જમીન <b>ઊંચી-નીચી કે રેતાળ</b> હોય તો 'ફુવારા' ચાલુ કરવા. અને જો વિસ્તારમાં <b>પાણી સાવ ઓછું જ</b> હોય, તો એક પણ ટીપું બગાડ્યા વિના સીધું મૂળમાં 'ટપક' પદ્ધતિ વાપરવી.</span></div>"
    },
    {
        chapter: 1,
        questionNumber: 7,
        marks: 3,
        q: "જો ઘઉંને ખરીફ ઋતુમાં ઉગાડવામાં આવે, તો શું થશે ? ચર્ચા કરો.",
        ans: "ઘઉં એ <b>રવી પાક</b> છે, એટલે કે તેને શિયાળાની ઋતુમાં (નવેમ્બર થી એપ્રિલ) ઉગાડવામાં આવે છે. ઘઉંના પાકને <b>ઠંડુ હવામાન અને મર્યાદિત માત્રામાં પાણીની જરૂર</b> હોય છે.<br><br>ખરીફ ઋતુ એટલે ચોમાસું (જૂન થી સપ્ટેમ્બર). જો ઘઉંને ખરીફ ઋતુમાં ઉગાડવામાં આવે તો નીચે મુજબની અસરો થશે:<br>૧. ચોમાસામાં સતત અને <b>વધુ વરસાદ પડવાને કારણે ઘઉંના બીજ સડી જશે</b> કે છોડ નાશ પામશે.<br>૨. ઘઉંને જરૂરી એવું ઠંડુ તાપમાન નહીં મળે.<br>૩. ચોમાસામાં ફૂગ અને રોગચાળો જલ્દી ફેલાય છે, જે પાકને નિષ્ફળ બનાવશે.<br>આથી, ઘઉંનું ઉત્પાદન થશે જ નહીં અને ખેડૂતને મોટું નુકસાન જશે.<br><br><div style='background-color:#ffebee; border-left:5px solid #f44336; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#b71c1c;'><b>નિતેશ સરની શોર્ટકટ ટ્રિક:</b><br>ઘઉંને શરદી (ઠંડી) બહુ ગમે છે! જો તમે તેને ચોમાસાના વરસાદમાં ઊભા રાખશો, તો તેને 'પાણી' લાગી જશે (ડૂબી જશે) અને પાક મરી જશે!</span></div>"
    },
    {
        chapter: 1,
        questionNumber: 8,
        marks: 3,
        q: "ખેતરમાં સતત પાક ઉગાડવાના લીધે જમીન પર કઈ અસર જણાશે ? સમજાવો.",
        ans: "ખેતરમાં એક જમીન પર એક પછી એક સતત પાક ઉગાડવાથી જમીન પર નીચે મુજબની માઠી અસર થાય છે:<br><br>૧. <b>પોષકતત્વોની ઉણપ:</b> દરેક પાક જમીનમાંથી અમુક ચોક્કસ પોષકતત્વો શોષે છે. સતત પાક લેવાથી જમીનમાં નાઇટ્રોજન, ફૉસ્ફરસ જેવા જરૂરી ખનિજ તત્વો ખૂટી જાય છે.<br>૨. <b>ફળદ્રુપતામાં ઘટાડો:</b> જમીનનો આરામ ન મળવાથી તેની ઉત્પાદન ક્ષમતા અને ફળદ્રુપતા ઘટી જાય છે. જમીન સાવ 'કંગાળ' બની જાય છે.<br>૩. <b>પાકનું ઉત્પાદન ઘટવું:</b> પોષકતત્વો વગર આવનારો નવો પાક નબળો પડે છે અને ઉત્પાદન સાવ ઘટી જાય છે.<br><br><b>ઉપાય:</b> આ પરિસ્થિતિ અટકાવવા ખેડૂતે બે પાક વચ્ચે ખેતરને થોડો સમય ખાલી છોડવું જોઈએ અથવા <b>પાકની ફેરબદલી</b> (Crop Rotation) કરવી જોઈએ.<br><br><div style='background-color:#fff3cd; border-left:5px solid #ffc107; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#856404;'><b>નિતેશ સરની ટિપ્સ:</b><br>જેમ તમને સતત 10 કલાક ભણાવવામાં આવે તો તમારું મગજ થાકી જાય અને કંઈ યાદ ન રહે, તેમ <b>જમીન પણ સતત પાક આપીને થાકી જાય છે!</b> તેને પણ આરામ કે 'બ્રેક' (પાકની ફેરબદલી) જોઈએ.</span></div>"
    },
    {
        chapter: 1,
        questionNumber: 9,
        marks: 3,
        q: "નીંદણ એટલે શું ? આપણે તેનું નિયંત્રણ કેવી રીતે કરી શકીએ છીએ ?",
        ans: "<b>નીંદણની વ્યાખ્યા:</b> ખેતરમાં મુખ્ય પાકની સાથે કુદરતી રીતે જ ઊગી નીકળતી બિનજરૂરી અને નકામી વનસ્પતિને <b>નીંદણ (Weeds)</b> કહે છે.<br><br><b>નિયંત્રણ (Weed Control) કરવાની રીતો:</b><br>૧. <b>ખેડ દ્વારા:</b> પાક ઉગાડતા પહેલાં ખેતર ખેડવાથી નીંદણ સુકાઈને મરી જાય છે અને માટીમાં ભળી જાય છે.<br>૨. <b>ભૌતિક રીત (હાથ વડે):</b> સમયાંતરે <b>ખુરપી અથવા દાતરડા</b>ની મદદથી નીંદણને જમીન નજીકથી કાપીને કે મૂળ સહિત જાતે જ ઉખેડી લેવામાં આવે છે.<br>૩. <b>રાસાયણિક રીત:</b> <b>2,4-D</b> જેવા નીંદણનાશક (Weedicides) રસાયણોનો પંપ દ્વારા ખેતરમાં છંટકાવ કરવામાં આવે છે. આનાથી નીંદણ નાશ પામે છે પરંતુ મુખ્ય પાકને નુકસાન થતું નથી.<br><br><div style='background-color:#e2e3e5; border-left:5px solid #6c757d; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#383d41;'><b>નિતેશ સરની શોર્ટકટ ટ્રિક:</b><br>નીંદણ એટલે આપણા પાકના ભોજનમાં ભાગ પડાવતો <b>'વણનોતર્યો મહેમાન'</b>! તેને કાઢવાના 3 રસ્તા: કાં તો શરૂઆતમાં જ કાઢી નાખો (ખેડ), કાં પકડીને બહાર કાઢો (ખુરપી), કાં દવાનો સ્પ્રે છાંટો (2,4-D).</span></div>"
    },
    {
        chapter: 1,
        questionNumber: 10,
        marks: 3,
        q: "નીચે આપેલાં બૉક્સને યોગ્ય ક્રમમાં ગોઠવો જેથી શેરડીના ઉત્પાદન માટેનું ક્રમદર્શી રેખાચિત્ર તૈયાર થઈ જાય :<br>1. પાકને ખાંડના કારખાનામાં મોકલવો<br>2. સિંચાઈ<br>3. લણણી<br>4. રોપણી<br>5. જમીન તૈયાર કરવી<br>6. ખેતરને ખેડવું<br>7. ખાતર આપવું",
        ans: "શેરડીના ઉત્પાદનનો સાચો ક્રમ (Flowchart) નીચે મુજબ છે:<br><br><div style='display:flex; flex-wrap:wrap; gap:10px; margin-top:15px; font-weight:bold; color:white; text-align:center;'><div style='background-color:#4CAF50; padding:10px; border-radius:5px; flex:1; min-width:120px;'>1. જમીન તૈયાર કરવી (Box 5)</div><div style='color:black; margin-top:10px;'>➔</div><div style='background-color:#8BC34A; padding:10px; border-radius:5px; flex:1; min-width:120px;'>2. ખેતરને ખેડવું (Box 6)</div><div style='color:black; margin-top:10px;'>➔</div><div style='background-color:#CDDC39; color:black; padding:10px; border-radius:5px; flex:1; min-width:120px;'>3. રોપણી (Box 4)</div><div style='color:black; margin-top:10px;'>➔</div><div style='background-color:#FFC107; color:black; padding:10px; border-radius:5px; flex:1; min-width:120px;'>4. ખાતર આપવું (Box 7)</div><div style='color:black; margin-top:10px;'>➔</div><div style='background-color:#03A9F4; padding:10px; border-radius:5px; flex:1; min-width:120px;'>5. સિંચાઈ (Box 2)</div><div style='color:black; margin-top:10px;'>➔</div><div style='background-color:#FF5722; padding:10px; border-radius:5px; flex:1; min-width:120px;'>6. લણણી (Box 3)</div><div style='color:black; margin-top:10px;'>➔</div><div style='background-color:#9C27B0; padding:10px; border-radius:5px; flex:1; min-width:120px;'>7. પાકને ખાંડના કારખાનામાં મોકલવો (Box 1)</div></div><br><br><div style='background-color:#e1f5fe; border-left:5px solid #03a9f4; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#01579b;'><b>નિતેશ સરની ટિપ્સ:</b><br>આખી જિંદગી યાદ રહે એવો લોજીકલ ક્રમ:<br>પહેલા પાયો (જમીન) બનાવો ➜ હળ ચલાવો ➜ બીજ વાવો ➜ ભૂખ લાગે તો ખાતર આપો ➜ તરસ લાગે તો પાણી (સિંચાઈ) ➜ પાકી જાય એટલે કાપો (લણણી) ➜ અને છેલ્લે વેચવા ફેક્ટરી મોકલો!</span></div>"
    },
    {
        chapter: 1,
        questionNumber: 11,
        marks: 4,
        q: "નીચે આપેલા સંકેતોની મદદથી આપેલો શબ્દ કોયડો તેનાં અંગ્રેજી નામ વડે પૂર્ણ કરો :<br>(Storage, Crop, Gram, Harvester, Winnowing, Irrigation)",
        ans: "આપેલા કોયડાના અંગ્રેજી જવાબો નીચે મુજબ છે:<br><br><b>ઊભી ચાવી (Down):</b><br>1. પાકને પાણી આપવું = <span style='color:#c2185b; font-weight:bold; letter-spacing:2px;'>IRRIGATION</span><br>2. પાકના દાણાઓને લાંબા સમય સુધી યોગ્ય સ્થિતિમાં રાખવા = <span style='color:#c2185b; font-weight:bold; letter-spacing:2px;'>STORAGE</span><br>5. વનસ્પતિ કે જેને મોટા પાયે ઉછેરવામાં આવે છે = <span style='color:#c2185b; font-weight:bold; letter-spacing:2px;'>CROP</span><br><br><b>આડી ચાવી (Across):</b><br>3. મશીન કે જે પરિપક્વ પાકને કાપવા માટે વપરાય છે = <span style='color:#1976d2; font-weight:bold; letter-spacing:2px;'>HARVESTER</span><br>4. રવીપાક કે જે એક કઠોળ પણ છે = <span style='color:#1976d2; font-weight:bold; letter-spacing:2px;'>GRAM</span> (ચણા)<br>6. ભૂસામાંથી દાણાઓને છૂટા પાડવાની પદ્ધતિ = <span style='color:#1976d2; font-weight:bold; letter-spacing:2px;'>WINNOWING</span> (ઉપણવું)<br><br><div style='background-color:#d4edda; border-left:5px solid #28a745; padding:10px; margin-top:10px; border-radius:4px;'>💡 <span style='color:#155724;'><b>નિતેશ સરની ટિપ્સ:</b><br>સ્પેલિંગ યાદ રાખવા માટે શબ્દોને તોડી નાખો: <b>IRRI-GATION, HAR-VESTER, WIN-NOW-ING.</b> આ સ્પેલિંગ એક-બે વાર રફ બુકમાં લખી લેવા, જેથી પરીક્ષામાં બોક્સમાં લખતી વખતે અક્ષરો ખૂટે નહીં!</span></div>"
    }
];
